# Generated by Django 6.1 on 2026-08-17 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('Fresher', 'Fresher'), ('0-1 Years', '0-1 Years'), ('1-3 Years', '1-3 Years'), ('3+ Years', '3+ Years')], max_length=50)),
                ('preferred_domain', models.CharField(max_length=100)),
                ('target_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_timeline', models.PositiveIntegerField(help_text='Timeline in months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
